
language: node_js
node_js:
  - "10.15"
sudo: false

branches:
  only:
    - master

env:
  global:
    - EXPO_SDK_VERSION="32.0.0"
    - TURTLE_VERSION="0.7.2"
    - YARN_VERSION="1.10.1"

jobs:
  include:
    - stage: publish app
      env:
        - CACHE_NAME=publish YARN_CACHE_FOLDER="/home/travis/yarn_cache"
      cache:
        directories:
          - $HOME/yarn_cache
      before_install:
        - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version $YARN_VERSION
        - export PATH="$HOME/.yarn/bin:$PATH"
      install:
        - yarn global add expo-cli
      script:
        - expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD --non-interactive
        - yarn
        - expo publish
    - stage: build standalone apps
      env:
        - CACHE_NAME=build-android-v2 YARN_CACHE_FOLDER="/home/travis/yarn_cache"
      cache:
        directories:
          - $HOME/.turtle
          - $HOME/yarn_cache
          - $HOME/.gradle/wrapper
      before_install:
        - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version $YARN_VERSION
        - export PATH="$HOME/.yarn/bin:$PATH"
      install:
        - pip install --user awscli
        - yarn global add gulp-cli turtle-cli@$TURTLE_VERSION
      script:
        - expo build:android
#        - export ARTIFACT_PATH="/home/travis/expo-project-$TRAVIS_COMMIT-`date +%s`.apk"
#        - turtle setup:android --sdk-version $EXPO_SDK_VERSION > /dev/null || travis_terminate 1
#        - echo $EXPO_ANDROID_KEYSTORE_BASE64 > expo-project.jks.base64
#        - base64 --decode expo-project.jks.base64 > expo-project.jks
#        - turtle build:android
#          --keystore-path ./expo-project.jks
#          --keystore-alias $EXPO_ANDROID_KEYSTORE_ALIAS
#          -o $ARTIFACT_PATH
